export { SpecialtyControllerService } from './services/specialty-controller.service';
export { RoleControllerService } from './services/role-controller.service';
export { RegistrationControllerService } from './services/registration-controller.service';
export { FormationControllerService } from './services/formation-controller.service';
export { DomainControllerService } from './services/domain-controller.service';
export { DocumentsControllerService } from './services/documents-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
export { UserControllerService } from './services/user-controller.service';
export { PersonControllerService } from './services/person-controller.service';
