services:
  postgres:
    container_name: poly_postgres
    image: postgres
    environment:
      POSTGRES_USER: prod_admin
      POSTGRES_PASSWORD: 9FD;ci|7P%q,&|28j$8#
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: centre-formation
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - centre-formation-network
    restart: unless-stopped

  bsn-api:
    container_name: centre-api
    image: ahmedtiba1993/centre-api:1.0.0
    ports:
      - 8088:8088
    networks:
      - centre-formation-network
    depends_on:
      - postgres

networks:
  centre-formation-network:
    driver: bridge

volumes:
  postgres:
    name: postgres-data
    driver: local