spring:
  datasource:
    url: jdbc:h2:file:./data/centre
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 2592000000
  cors:
    origins: http://localhost:4200/

management:
  endpoints:
    web:
      exposure:
        include: health